-- insert into user(id, name, surname, join_date) values (1, 'Lech', 'Walesa', '2019-01-01 19:45');
-- insert into user(id, name, surname, join_date) values (2, 'Andrzej', 'Duda', '2019-01-01 19:45');
-- insert into user(id, name, surname, join_date) values (3, 'Aleksander', 'Kwasniewski', '2019-01-01 19:45');
--
-- insert into post (id, message, user_id) values (1, 'My first post', 2)
-- insert into post (id, message, user_id) values (2, 'My first post', 1)
-- insert into post (id, message, user_id) values (3, 'My first post', 1)
--
--
-- insert into user_credentials(login, password, role, user_id) values ('lech', 'lech', 'user', 1)